name: Jamz Entertainment LLC
favicon: null
layout_spectrum: 0.50143
typography_spectrum: 0.98983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#707070'
    - '#020203'
    - '#303030'
    - '#ffffff'
    - '#bcd5fb'
  brandStrength: 0.4375
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
