name: Jamz Entertainment LLC
favicon: null
layout_spectrum: 0.50143
typography_spectrum: 0.98983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8c8c8c'
    - '#484848'
    - '#cbcbcb'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
